templates: []
mode: train
resume_training: false
pilot: false
pretrained_weights: null
num_users: null
num_items: null
num_ratings: null
num_days: null
local_data_folder: ./Data
dataset_code: ml-1m
min_rating: 0
min_uc: 5
min_sc: 5
split: leave_one_out
dataloader_code: vae
dataloader_random_seed: 0.0
train_batch_size: 512
val_batch_size: 512
test_batch_size: 512
train_window: 16
dataloader_output_timestamp: false
dataloader_output_days: false
dataloader_output_user: false
train_negative_sampler_code: random
train_negative_sample_size: 0
train_negative_sampling_seed: 0
test_negative_sampler_code: popular
test_negative_sample_size: 100
test_negative_sampling_seed: 98765
weight_type: exp_stair
weight_constant: 4
trainer_code: vae
device: cuda
use_parallel: true
num_workers: 0
optimizer: Adam
lr: 0.005
weight_decay: 0.00001
momentum: null
decay_step: 16
gamma: 0.9
clip_grad_norm: 5.0
num_epochs: -1
log_period_as_iter: 12800
metric_ks:
- 1
- 5
- 10
- 20
- 50
- 100
best_metric: NDCG@10
saturation_wait_epochs: 20
total_anneal_steps: 200000
anneal_cap: 0.2
train_transfer: true
best_model_transfer: true
model_code: vae
dropout: 0.5
encoder_hidden_layer:
- 512
max_len: 128
encode_len: 128
model_init_seed: 0
model_init_range: 0.02
output_info: false
experiment_root: experiments
experiment_group: test
experiment_name: vae
wandb_project_name: null
wandb_run_name: null
wandb_run_id: null
meta: training
